name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ "**" ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    services:
      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping || exit 1"
          --health-interval 5s
          --health-timeout 3s
          --health-retries 20

    env:
      REDIS_ADDR: localhost:6379
      REDIS_PASSWORD: ""
      REDIS_DB: "0"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Go version
        run: go version

      - name: Download modules
        run: go mod download

      - name: Formatting
        run: |
          files=$(gofmt -s -l .)
          if [ -n "$files" ]; then
            echo "gofmt found unformatted files:" >&2
            echo "$files" >&2
            echo "Run 'go fmt ./...' locally and commit the changes." >&2
            exit 1
          fi

      - name: Vet
        run: go vet ./...

      - name: Test
        run: go test -v ./...
